org.gradle.jvmargs=-Xmx3072M
minecraft_version=1.21
java_version=21
enabled_platforms=fabric,forge
archives_base_name=playeranimatorapi
mod_id=playeranimatorapi
mod_version=2.3.8
maven_group=zigy.playeranimatorapi
fabric_loader_version=0.15.11
fabric_api_version=0.100.6+1.21
neoforge_version=21.0.114-beta
parchment_version=2024.07.07
player_anim_version=2.0.1+1.21.1
azurelib_version=2.3.14
geckolib_version=4.5.8
multiloader_utils_version=1.3.0
pehkui_version=3.8.3
