modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/ZigyTheBird/ZigysPlayerAnimatorAPI/issues"
license = "MIT License"

[[mixins]]
config = "playeranimatorapi-common.mixins.json"
[[mixins]]
config = "playeranimatorapi.mixins.json"

[[mods]]
modId = "playeranimatorapi"
version = "2.3.0"
displayName = "Zigy's Player Animator API"
authors = "Zigy"
description = '''
API for playing player animations from server side.
'''

logoFile = "icon.png"

[[dependencies.playeranimatorapi]]
modId = "neoforge"
type="required"
versionRange = "[21.0.000-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.playeranimatorapi]]
modId = "minecraft"
type="required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.playeranimatorapi]]
modId = "playeranimator"
type="required"
versionRange = "[2.0.1+1.21.1,)"
ordering = "AFTER"
side = "CLIENT"