plugins {
    id "com.github.johnrengelman.shadow" version "7.1.2"
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin because we don't want IDEA to index this.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common
}

dependencies {
    neoForge "net.neoforged:neoforge:${rootProject.neoforge_version}"

    modImplementation "com.zigythebird.multiloaderutils:zigysmultiloaderutils-neoforge-$rootProject.minecraft_version:$rootProject.multiloader_utils_version"
    include "com.zigythebird.multiloaderutils:zigysmultiloaderutils-neoforge-$rootProject.minecraft_version:$rootProject.multiloader_utils_version"

    modApi("com.github.Virtuoel:Pehkui:$rootProject.pehkui_version-$rootProject.minecraft_version-neoforge")

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionNeoForge")) { transitive false }

    modImplementation("software.bernie.geckolib:geckolib-neoforge-${minecraft_version}:${geckolib_version}")
    modImplementation "mod.azure.azurelib:azurelib-neo-$rootProject.minecraft_version:$rootProject.azurelib_version"

    modImplementation "dev.kosmx.player-anim:player-animation-lib-forge:${rootProject.player_anim_version}"

//    modImplementation "curse.maven:emotecraft-forge-403422:4632460"
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    filesMatching("META-INF/mods.toml") {
        expand "version": rootProject.version, "player_anim_version": rootProject.player_anim_version
    }
}

shadowJar {
    exclude "fabric.mod.json"

    configurations = [project.configurations.shadowCommon]
}

remapJar {
    input.set shadowJar.archiveFile
    dependsOn shadowJar
}

jar {
    archivesBaseName = "$mod_id-neoforge-$minecraft_version"
}

sourcesJar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}

publishing {
    repositories {
        maven {
            name = "zigythebirdmods"
            url = "https://maven.zigythebird.com/mods"
            credentials(PasswordCredentials)
            authentication {
                basic(BasicAuthentication)
            }
        }
    }
    publications {
        maven(MavenPublication) {
            groupId = "com.zigythebird.playeranimatorapi"
            artifactId = "$mod_id-neoforge-$minecraft_version"
            version = rootProject.mod_version
            from components.java
        }
    }
}
