name: Publish on CurseForge & Modrinth

on: [ workflow_dispatch ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          # Only include this section if you wish to publish
          # your assets on Modrinth.
          modrinth-id: IkQufrWh
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          # Only include this section if you wish to publish
          # your assets on CurseForge.
          curseforge-id: 958083
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          
          files: neoforge/build/libs/!(*-@(dev|sources|javadoc)).jar neoforge/build/libs/*-@(dev|sources|javadoc).jar fabric/build/libs/!(*-@(dev|sources|javadoc)).jar fabric/build/libs/*-@(dev|sources|javadoc).jar