name: Publish on Modrinth & CurseForge

on:
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        description: Which branch do you want to publish?
        options:
        - dev
        - 1.21
        - 1.20.4
        - 1.20.1
      forge:
        type: choice
        description: NeoForge or Forge?
        options:
        - neoforge
        - forge

jobs:
  build_dev:
    uses: zigythebird/zigysplayeranimatorapi/.github/workflows/releasebuild.yml@dev
    with:
      branch: ${{ inputs.branch }} 
      GITHUB_REF: ${{ github.ref }}
      upload_docs: true
      forge: ${{ inputs.forge }}
    secrets:
      CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
