name: Publish on Modrinth & CurseForge

on:
  workflow_dispatch:
    inputs:
      forge:
        type: choice
        description: NeoForge or Forge?
        options:
        - neoforge
        - forge

jobs:
  build_dev:
    uses: zigythebird/zigysplayeranimatorapi/.github/workflows/releasebuild.yml@dev
    with:
      branch: ${{ github.head_ref || github.ref_name }} 
      GITHUB_REF: ${{ github.ref }}
      upload_docs: true
      forge: ${{ inputs.forge }}
    secrets:
      CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}