name: Publish on Modrinth & CurseForge

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to publish.'
        type: environment
        required: true

jobs:

  build_dev:
    uses: zigythebird/zigysplayeranimatorapi/.github/workflows/releasebuild.yml@dev
    with:
      branch: ${{ inputs.branch }}
      GITHUB_REF: ${{ github.ref }}
      upload_docs: true
      forge: neoforge
    secrets:
      CF_API_KEY: ${{ secrets.CURSEFORGE_KEY }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}