name: Publish Dev Branch

on: [ workflow_dispatch ]

jobs:

  build_dev:
    uses: zigythebird/zigysplayeranimatorapi/.github/workflows/releasebuild.yml@main
    with:
      branch: dev
      GITHUB_REF: ${{ github.ref }}
      upload_docs: true
      forge: neoforge
    secrets:
      CF_API_KEY: ${{ secrets.CURSEFORGE_KEY }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}